### ISSUE TITLE
Min/Max für Leistung und Phasenwinkel einblenden

### ISSUE THREAD

**Issue by matthias-mueller** [jacmendt/messnetz-client-piratenpv#4]
... sonst hat man in der Standardansicht den Eindruck, dass sich die Werte (bei Lucas) kaum verändern. Die schwanken aber sehr stark, sobald man weit reinzoomt.

**Comment by jacmendt** [comment]
Min-/Max- für Firma Lucas ist deswegen etwas problematisch, da es Dummy-Werte sind und die streuen halt über den gesamten Wertebereich. Das sieht entsprechend überladen aus. Aber wenn es so sehr irritiert kann ich es wieder rein bringen.

**Comment by matthias-mueller** [comment]
... weil darin auch zwei Datenreihen gleichzeitig dargestellt sind; verstehe ich. Vielleicht fällt die ja ne gute Lösung ein ...

**Comment by jacmendt** [comment]
Fiese Antwort :P

**Comment by matthias-mueller** [comment]
Ich weiß. Aber irgend ne Art von Bereichsanzeige im Diagramm wäre sinnvoll. Was hältst du längerfristig von einem Chart-Switcher (analog zu Layerswitchern in Karten). Darin könnte man dann die min/max/coverage properties ein- und ausblenden.

**Comment by matthias-mueller** [comment]
Vlt. kannst du bei überlagerten Zeitreihen für die min/max-Geschichten erstmal mit Transparenz arbeiten? Das sollte halbwegs passabel aussehen.

**Comment by jacmendt** [comment]
Kann man mal diskutieren bzw. versuchen. Bzgl. dieser Anwendung schaue ich aber jetzt erstmal was mit den gegebenen Mitteln möglich ist.

Mit Transparenz arbeite ich schon. Ich schalte Sie nachher an und dann kannst du es dir mal anschauen :)

**Comment by matthias-mueller** [comment]
OK, sieht wirklich nicht so schön aus. Wie wärs denn statt der Flächen 
einfache min/max-Linien im Diagramm einzuziehen?
